name: Python DevOps CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Unit Tests
        run: pytest


      #incomplete needs to insert secrets.
      - name: Log in to GHCR
        uses: docker/login-action@v3
      
      #comptele the actions and vm ssh config
     
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        

      
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        
